### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId" : 1,
  "accountNumber" :  "4040026797",
  "amount" : 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId" : "transactionId",
  "accountNumber" :  "1000000000",
  "amount" : 1000
}

### query transaction
GET http://localhost:8080/transaction/df8684fb52dc434c938ea09a0ea50cb7